os: linux
files:
  - source: /
    destination: /var/www
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 30
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 3600